#!/usr/bin/env node
// sv-seed.js -- dev workaround for the 1.60.1 beta client, which writes
// SavedVariables at logout and never reads them back.
//
// Copies the addon's saved files from WTF into Dev/SavedSeed.lua, which the TOC
// loads as ordinary addon code; ns:InitDB (Core/Database.lua) takes the seed
// only while the client itself delivers nothing.
//
//   node sv-seed.js            one copy, now
//   node sv-seed.js --watch    keep copying whenever the client saves (leave it
//                              running while you play; covers /reload too)
//   node sv-seed.js --clear    put the empty stub back
//   --wow <dir>                client folder (default: env WOW_FOREVER_DIR, then
//                              the standard _classic_beta_ install path)
//
// The saved files are executed as addon code by the client, so nothing is
// copied unless it parses and consists of plain assignments to our own two
// variables.
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const luaparse = require('luaparse');

const ROOT = path.resolve(__dirname, '..');
const ADDON = 'VuloForeverUI';
const ACCOUNT_VAR = 'VuloForeverUIDB';
const CHAR_VAR = 'VuloForeverUICharDB';
const SEED_REL = path.join('Dev', 'SavedSeed.lua');
const SEED = path.join(ROOT, SEED_REL);
const POLL_MS = 250;

const args = process.argv.slice(2);
const flag = name => args.includes(name);
const wowArg = args.indexOf('--wow');
const WOW = (wowArg >= 0 && args[wowArg + 1])
    || process.env.WOW_FOREVER_DIR
    || 'C:\\Program Files (x86)\\World of Warcraft\\_classic_beta_';

const STUB = [
    '-- VuloForeverUI / Dev / SavedSeed',
    '-- DEV ONLY. The 1.60.1 beta client writes SavedVariables at logout and never',
    '-- reads them back (docs/forever-client-research.md), so every login starts from',
    '-- defaults. `node tools/sv-seed.js` overwrites this file with a copy of the',
    '-- saved files from WTF; ns:InitDB uses it only while the client delivers',
    '-- nothing itself. This committed version is the empty stub -- it carries no',
    '-- data and does nothing.',
    '',
].join('\n');

function stamp(d) {
    const p = n => String(n).padStart(2, '0');
    return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate())
        + ' ' + p(d.getHours()) + ':' + p(d.getMinutes()) + ':' + p(d.getSeconds());
}

// Every SavedVariables/<addon>.lua below WTF/Account, however deep: the beta
// nests characters as <account>/<id>/<Name-Realm>/, older clients as
// <account>/<Realm>/<Name>/.
function findSaved() {
    const base = path.join(WOW, 'WTF', 'Account');
    const found = [];
    const visit = (dir, depth) => {
        let entries;
        try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch (e) { return; }
        for (const e of entries) {
            if (!e.isDirectory()) continue;
            const p = path.join(dir, e.name);
            if (e.name === 'SavedVariables') {
                const f = path.join(p, ADDON + '.lua');
                if (fs.existsSync(f)) found.push({ file: f, depth, owner: dir });
            } else if (depth < 3) {
                visit(p, depth + 1);
            }
        }
    };
    visit(base, 0);
    return found;
}

// depth 1 = <account>/SavedVariables; anything deeper is a character.
function charKey(owner) {
    const name = path.basename(owner);
    if (name.includes('-')) return name;
    return name + '-' + path.basename(path.dirname(owner));
}

// Returns the source if it is safe to run as addon code, otherwise null.
function readChecked(file, varName) {
    let src;
    try { src = fs.readFileSync(file, 'utf8'); } catch (e) { return null; }
    if (src.charCodeAt(0) === 0xFEFF) src = src.slice(1);
    let ast;
    try { ast = luaparse.parse(src, { luaVersion: '5.1' }); } catch (e) { return null; }  // half-written
    for (const st of ast.body) {
        const ok = st.type === 'AssignmentStatement'
            && st.variables.length === 1
            && st.variables[0].type === 'Identifier'
            && st.variables[0].name === varName
            && st.init.length === 1
            && (st.init[0].type === 'TableConstructorExpression' || st.init[0].type === 'NilLiteral');
        if (!ok) return null;
    }
    return ast.body.length ? src : null;
}

function build() {
    const saved = findSaved();
    const byTime = (a, b) => fs.statSync(a.file).mtimeMs - fs.statSync(b.file).mtimeMs;
    const accounts = saved.filter(s => s.depth === 1).sort(byTime);
    const chars = saved.filter(s => s.depth > 1).sort(byTime);   // oldest first: newest wins a key clash

    const out = [
        '-- GENERATED by tools/sv-seed.js from the client\'s saved files -- do not edit,',
        '-- do not commit (`node tools/sv-seed.js --clear` restores the stub).',
        'local _, ns = ...',
        'local seed = { stamp = "' + stamp(new Date()) + '", chars = {} }',
        'ns._svSeed = seed',
    ];
    let parts = 0;
    const account = accounts[accounts.length - 1];
    if (account) {
        const src = readChecked(account.file, ACCOUNT_VAR);
        if (src === null) return null;
        // The local shadows the global, so the file's own assignment lands here.
        out.push('do', 'local ' + ACCOUNT_VAR, src.trim(), 'seed.account = ' + ACCOUNT_VAR, 'end');
        parts++;
    }
    for (const c of chars) {
        const src = readChecked(c.file, CHAR_VAR);
        if (src === null) return null;
        out.push('do', 'local ' + CHAR_VAR, src.trim(),
            'seed.chars[' + JSON.stringify(charKey(c.owner)) + '] = ' + CHAR_VAR, 'end');
        parts++;
    }
    if (!parts) return { text: null, parts: 0 };
    const text = out.join('\n') + '\n';
    luaparse.parse(text, { luaVersion: '5.1' });   // the client must never see a broken seed
    return { text, parts, chars: chars.length };
}

function writeAtomic(text) {
    fs.mkdirSync(path.dirname(SEED), { recursive: true });
    const tmp = SEED + '.tmp';
    fs.writeFileSync(tmp, text);
    fs.renameSync(tmp, SEED);
}

// The stub is tracked so the TOC entry always resolves; the generated copy holds
// personal settings and must not show up as a change to commit.
function gitSkip(on) {
    try {
        execFileSync('git', ['update-index', on ? '--skip-worktree' : '--no-skip-worktree',
            SEED_REL.replace(/\\/g, '/')], { cwd: ROOT, stdio: 'ignore' });
        return true;
    } catch (e) { return false; }
}

function seedOnce(quiet) {
    let res;
    try { res = build(); } catch (e) { console.log('seed not written: ' + e.message); return false; }
    if (res === null) { if (!quiet) console.log('a saved file is unreadable or not plain data -- nothing written'); return false; }
    if (!res.parts) { if (!quiet) console.log('no saved files for ' + ADDON + ' under ' + WOW); return false; }
    let current = null;
    try { current = fs.readFileSync(SEED, 'utf8'); } catch (e) { /* first run */ }
    const body = t => t && t.replace(/stamp = "[^"]*"/, '');
    if (body(current) === body(res.text)) return true;
    writeAtomic(res.text);
    console.log(stamp(new Date()) + '  seed written: account + ' + res.chars + ' character file(s)');
    if (!gitSkip(true)) {
        console.log('  note: ' + SEED_REL + ' is not tracked by git yet -- commit the stub first');
        console.log('  (`node tools/sv-seed.js --clear`, commit, run this again) so the seed never gets committed.');
    }
    return true;
}

if (flag('--clear')) {
    writeAtomic(STUB);
    gitSkip(false);
    console.log('stub restored');
} else if (flag('--watch')) {
    console.log('watching ' + path.join(WOW, 'WTF') + '  (Ctrl+C to stop)');
    seedOnce(false);
    let last = '';
    setInterval(() => {
        const sig = findSaved().map(s => {
            try { const st = fs.statSync(s.file); return s.file + st.mtimeMs + ':' + st.size; } catch (e) { return ''; }
        }).join('|');
        // A half-written file fails the check and leaves `last` alone, so the
        // next tick tries again.
        if (sig !== last && seedOnce(true)) last = sig;
    }, POLL_MS);
} else {
    process.exitCode = seedOnce(false) ? 0 : 1;
}
